In [2]:
import numpy as np 
import sys

In [5]:
a = np.array([2,3,6])
b = np.array([8,3,7])

In [8]:
print(a)
print(b)

[2 3 6]
[8 3 7]


In [9]:
c = a*b

In [10]:
c.dtype 

dtype('int32')

In [11]:
c.data

In [13]:
c.itemsize

4

In [14]:
c

array([16,  9, 42])